server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystores/otherkeystore.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD:123456}
server.ssl.key-alias=otherkeypair
server.ssl.enabled=true
